services:
  url-shortener:
    build: .
    image: url_shortener
    ports:
      - '8080:8080'
    depends_on:
      - mongodb

  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_admin_pass
    volumes:
      - 'mongo-volume:/data/db'


  mongo-express:
    image: 'mongo-express'
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo_admin:mongo_admin_pass@mongodb:27017/
      # Credential to Mongo Express UI
      ME_CONFIG_BASICAUTH_USERNAME: mongo_debug
      ME_CONFIG_BASICAUTH_PASSWORD: qwerty
    depends_on:
      - mongodb
    profiles:
      - debug

  prometheus:
    image: prom/prometheus
    volumes:
      - './prometheus-grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - 'prometheus-volume:/prometheus'
    restart: always
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    depends_on:
      - prometheus
    restart: always
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
        - './prometheus-grafana/grafana/provisioning/datasource:/etc/grafana/provisioning/datasources'
        - './prometheus-grafana/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards'
        - 'grafana-volume:/var/lib/grafana'

volumes:
  mongo-volume:
  grafana-volume:
  prometheus-volume:
