global:
  scrape_interval: 15s
  scrape_timeout: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: url-shortener
    scrape_interval: 15s
    scrape_timeout: 10s

    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'url-shortener:8080'